#' ChatGPT: Explain Code
#'
#' @param code The code to be explained by ChatGPT.
#'
#' @importFrom clipr read_clip
#' @importFrom stringr str_replace_all
#'
#' @examples
#' \dontrun{
#' cat(explain_code("for (i in 1:10) {\n  print(i ** 2)\n}"))
#' }
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
explain_code <- function(code = NULL) {

  if (is.null(code)) {
    code <- read_clip(allow_non_interactive = TRUE)
  }

  if (is.null(code)) {
    stop("Add your code as an argument of copy code to clipboard")
  } else {
    code <- paste(str_replace_all(code, "\"", "'"), collapse = "\n")
  }

  prompt <- paste0('Explain the following R code: "', code, '"')
  parse_response(gpt_get_completions(prompt))
}
